<head>
<script type="text/javascript"
	src="//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_HTMLorMML">
</script>
<script
	src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">jquery</script>
<script type="text/javascript">
	function f(x) {alert(x)}
	var queue = MathJax.Callback.Queue([f, 'a'], [f, 10], [f, 5]);
	queue.Push([f, 0]);
	</script>
</head>
<div>
    <?php echo $this->getContent(); ?>
</div>