<script type="text/javascript">
var math = document.getElementById("view-question");
MathJax.Hub.Queue(["Typeset",MathJax.Hub]);
$(document).ready(function(){
	$("#name").keydown(function(){
		$("#view-question").html("<p>\(\frac a b\)</p>");
		});
});
</script>
<h1>Tạo đề thi</h1>
<div id="view-question">Question</div>
<p >TeX: \(\frac a b\)</p>
<p>
	MathML:
	<math>
		<msqrt>
		<mi>x</mi></msqrt></math>
</p>
<p>`a^2 + b^2 = c^2`</p>
<?php echo $question->render("name")?>