<h1>Đăng ký tài khoản</h1>
<div>
	<form action='register' method="post">
		<table>
			<tr>
				<td>User name</td>
				<td><input type='text' name='user_name' required></td>
			</tr>
			<tr>
				<td>Password</td>
				<td><input type='password' name='password' required></td>
			</tr>
			<tr>
				<td>Nhập lại password</td>
				<td><input type='password' name='password' required></td>
			</tr>
			<tr>
				<td>Tên</td>
				<td><input type='text' name='first_name' required></td>
			</tr>
			<tr>
				<td>Họ</td>
				<td><input type='text' name='last_name'></td>
			</tr>
			<tr>
				<td>Email</td>
				<td><input type="email" name='email' required></td>
			</tr>
			<tr>
				<td><input type="submit" name='register' value='Register'></td>
			</tr>
		</table>
	</form>
</div>