<h1>Đăng ký tài khoản</h1>
<form action='register' method="post">
	<label>User name</label><input type='text' name='user_name'><br /> <label>Password</label><input
		type='password' name='password'><br /> <label>First name</label><input
		type='text' name='first_name'><br /> <label>Email</label><input
		type="email" name='email'><br> <input type="submit" name='register'
		value='Register'>
</form>